# Generated by Django 3.2.6 on 2021-08-11 06:23

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0004_delete_poststatistic'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug_en',
            field=models.SlugField(null=True, unique=True, verbose_name='URL для категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug_ru',
            field=models.SlugField(null=True, unique=True, verbose_name='URL для категории'),
        ),
        migrations.AddField(
            model_name='like',
            name='post_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_for_like', to='posts.post', verbose_name='Пост'),
        ),
        migrations.AddField(
            model_name='like',
            name='post_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_for_like', to='posts.post', verbose_name='Пост'),
        ),
        migrations.AddField(
            model_name='like',
            name='user_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='like',
            name='user_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='post',
            name='category_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.category', verbose_name='Категория поста'),
        ),
        migrations.AddField(
            model_name='post',
            name='category_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.category', verbose_name='Категория поста'),
        ),
        migrations.AddField(
            model_name='post',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='slug_en',
            field=models.SlugField(null=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='post',
            name='slug_ru',
            field=models.SlugField(null=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en',
            field=models.CharField(max_length=70, null=True, verbose_name='Название статьи'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ru',
            field=models.CharField(max_length=70, null=True, verbose_name='Название статьи'),
        ),
    ]
